steps:
  # Set new line
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    id: 'set-project-file'
    entrypoint: bash
    args:
      - -c
      - |
        if [ -f "${_PROJECT_FILE}" ]; then
          echo "Preparing file: ${_PROJECT_FILE}"
          # new line
          echo "" >> "${_PROJECT_FILE}"
        else
          echo "*** Error: Project file '${_PROJECT_FILE}' not found!"
          exit 1
        fi
    # Run script
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    id: 'run-snapshot'
    entrypoint: bash
    env:
      - 'PROJECT_FILE=${_PROJECT_FILE}'
    args:
      - -c
      - |
        chmod +x snapshot_script.sh
        echo "Executing snapshot_script.sh with project file: ${_PROJECT_FILE}"
        ./snapshot_script.sh "${_PROJECT_FILE}"

substitutions:
  _PROJECT_FILE: "batch1_nonprod"   

timeout: 7200s

options:
  logging: CLOUD_LOGGING_ONLY