steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    id: 'create-snapshots'
    entrypoint: bash
    env:
      - 'BATCH_FILE=${_BATCH_FILE}'
    args:
      - '-c'
      - |
        echo "====================================================="
        echo "Starting snapshot creation for batch: ${BATCH_FILE}"
        echo "====================================================="

        FILE_PATH="project_lists/${BATCH_FILE}.txt"
        echo "Using project list file: $FILE_PATH"

        if [[ ! -f "$FILE_PATH" ]]; then
          echo "Error: Project list file '$FILE_PATH' not found!"
          exit 1
        fi

        chmod +x snapshot_script.sh
        ./snapshot_script.sh "$FILE_PATH"

substitutions:
  _BATCH_FILE: "batch1_nonprod"

timeout: "3600s"
options:
  logging: CLOUD_LOGGING_ONLY
